---
- name: Deploy / build server
  hosts: deploy


- name: Manager
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig
    - role: swarm_join
      type: manager
      tags: swarm_join

- name: Worker
  hosts: workers
  roles:
    - role: preconfig
      tags: preconfig
    - role: swarm_join
      type: worker
      tags: swarm_join
